# Systems of Linear Equations - Quiz

## Introduction
Following scenarios present problems that can be solved as system of equations, while performing substitutions and eliminations as we saw in the previous lesson. 

* Solve these problems by hand, showing all the steps to work out the unknown variable values 
* Verify your answers by showing the calculated values satisfy all equations

## Objectives
You will be able to:
* Describe a system of linear equations for solving simple analytical problems
* Solve a system of equations using elimination and substitution

## Exercise 1
#### Joe paid 12 dollars for 4 cups of coffee and 4 cups of tea. 3 cups of coffee cost as much as 2 cups of tea. 

#### What would be the total cost of 5 cups of coffee and 5 cups of tea ?

## Solution

> Let x be the unit price of coffee and y be the unit price of tea

In [1]:
# Your solution here 
import numpy as np

In [66]:
def solve_2x2(a, b, c, d, s1, s2):
    coef_  = np.matrix([[a, b], [c, d]])
    values = np.matrix([[s1], [s2]])
    x, y = np.dot(np.linalg.inv(coef_), values)
    return x[0], y[0]

In [67]:
coef_  = np.matrix([[4,  4], [3, -2]])
values = np.matrix([[12], [0]])
print(coef_)
print(values)

[[ 4  4]
 [ 3 -2]]
[[12]
 [ 0]]


In [68]:
x, y = np.dot(np.linalg.inv(coef_), values)

In [69]:
5*x + 5*y

matrix([[15.]])

In [70]:
x, y = solve_2x2(4, 4, 3, -2, 12, 0)
5*x + 5*y

matrix([[15.]])

## Exercise 2

#### Jim has more money than Bob.  If Jim gave Bob 20 dollars , they would have the same amount.  While if Bob gave Jim 22 dollars, Jim would then have twice as much as Bob. 

#### How much does each one actually have?

## Solution
> Let x be the amount of money that Jim has and y be the amount that Bob has.

In [71]:
# Your solution here 
# x - 20 = y + 20
# x + 22 = 2*(y - 22)

coef_  = np.matrix([[1, -1], [1, -2]])
values = np.matrix([[40], [-66]])

In [72]:
jim, bob = np.dot(np.linalg.inv(coef_), values)
print(jim, bob)

[[146.]] [[106.]]


In [74]:
x, y = solve_2x2(1, -1, 1, -2, 40, -66)
x, y

(matrix([[146.]]), matrix([[106.]]))

## Exercise 3

#### Mia has 30 coins, consisting of quarters (25 cents) and dimes (10 cents), which total to the amount 5.70 dollars.  
#### How many of each does she have?

In [75]:
# Your solution here 
# q + d = 30
# 25q + 10d = 570
q, d = solve_2x2(1, 1, 25, 10, 30, 570)
q, d

(matrix([[18.]]), matrix([[12.]]))

## Level up - Optional 
For more pratice with linear equations, Visit following links for more complex equations and online answers verification:

* https://www.transum.org/software/SW/Starter_of_the_day/Students/Simultaneous_Equations.asp?Level=6
* https://www.transum.org/software/SW/Starter_of_the_day/Students/Simultaneous_Equations.asp?Level=7

## Summary
In this lesson, we saw how to solve linear equations by hand to find the co-efficient values. We shall now move forward to have a deeper look into vectors and matrices and how Python and Numpy can help us solve more complex equations in an analytical context. 